#sbs-git:slp/unmodified/speex speex 1.2rc1 9bb0e6afe6171ab1c8764f46a809cfa83be7c0d4
# 
# Do not Edit! Generated by:
# spectacle version 0.14
# 

Name:       speex
Summary:    A voice compression format (codec)
Version:    1.2rc1
Release:    5
Group:      System/Libraries
License:    BSD
URL:        http://www.speex.org/
Source0:    %{name}-%{version}.tar.gz
Requires(post):  /sbin/ldconfig
Requires(postun):  /sbin/ldconfig
BuildRequires:  pkgconfig(ogg)

%description
Speex is a patent-free compression format designed especially for
speech. It is specialized for voice communications at low bit-rates in
the 2-45 kbps range. Possible applications include Voice over IP
(VoIP), Internet audio streaming, audio books, and archiving of speech
data (e.g. voice mail).



%package tools
Summary:    The tools package for %{name}
Group:      Applications/Multimedia
Requires:   %{name} = %{version}-%{release}

%description tools
Speex is a patent-free compression format designed especially for
speech. This package contains tools files and user's manual for %{name}.


%package devel
Summary:    Development package for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Speex is a patent-free compression format designed especially for
speech. This package contains development files for %{name}



%prep
%setup -q -n %{name}-1.2rc1


%build

%configure -disable-static \
%ifarch %arm
	--enable-arm5e-asm \
	--disable-oggtest \
	--disable-float-api \
	--disable-vbr \
	--enable-fixed-point 
%endif

make %{?jobs:-j%jobs}

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/license
cp COPYING %{buildroot}/usr/share/license/%{name}
%make_install

rm -f $RPM_BUILD_ROOT%{_docdir}/speex/manual.pdf



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig




%files
%manifest speex.manifest
%defattr(-,root,root,-)
%doc COPYING
%{_libdir}/libspeex*.so.*
/usr/share/license/%{name}

%files tools
%manifest tools.manifest
%defattr(-,root,root,-)
%{_bindir}/speexenc
%{_bindir}/speexdec
%doc %{_mandir}/man1/speexenc.1*
%doc %{_mandir}/man1/speexdec.1*

%files devel
%defattr(-,root,root,-)
%doc doc/manual.pdf
%{_includedir}/speex
%{_datadir}/aclocal/speex.m4
%{_libdir}/pkgconfig/speex*.pc
%{_libdir}/libspeex*.so

